# Generated by Django 4.2.7 on 2026-02-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otps',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('required_items', models.JSONField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('FUNDED', 'Funded'), ('SUPPLIER_ASSIGNED', 'Supplier Assigned'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('FIELD_OFFICER_ASSIGNED', 'Field Officer Assigned'), ('FIELD_OFFICER_CONFIRMED', 'Field Officer Confirmed'), ('IN_DISTRIBUTION', 'In Distribution'), ('COMPLETED', 'Completed')], default='CREATED', max_length=30)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_reports',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('DONOR', 'Donor'), ('NGO', 'NGO'), ('SUPPLIER', 'Supplier'), ('FIELD_OFFICER', 'Field Officer'), ('ADMIN', 'Admin')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SupplierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('confirmed', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_assignments', to='api.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.user')),
            ],
            options={
                'db_table': 'supplier_assignments',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='api.user'),
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donor_signature', models.CharField(max_length=255)),
                ('ngo_signature', models.CharField(max_length=255)),
                ('blockchain_tx', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='api.project')),
            ],
            options={
                'db_table': 'fundings',
            },
        ),
        migrations.CreateModel(
            name='FieldOfficerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assignments', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_officer_assignments', to='api.project')),
            ],
            options={
                'db_table': 'field_officer_assignments',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_scan_verified', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='api.beneficiary')),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='api.project')),
            ],
            options={
                'db_table': 'distributions',
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='api.project'),
        ),
    ]
