# Generated by Django 4.2.7 on 2026-02-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_project_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierassignment',
            name='delivery_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierassignment',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierassignment',
            name='field_officer_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assignments', to='api.user'),
        ),
        migrations.AddField(
            model_name='supplierassignment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
