# Generated by Django 4.2.7 on 2026-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supplierassignment_delivery_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING_FUNDING', 'Pending Funding'), ('FUNDED', 'Funded'), ('SUPPLIER_ASSIGNED', 'Supplier Assigned'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('FIELD_OFFICER_ASSIGNED', 'Field Officer Assigned'), ('FIELD_OFFICER_CONFIRMED', 'Field Officer Confirmed'), ('IN_DISTRIBUTION', 'In Distribution'), ('COMPLETED', 'Completed')], default='PENDING_FUNDING', max_length=30),
        ),
    ]
