# Generated by Django 4.2.7 on 2026-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_face_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='funding',
            name='donor_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='funding',
            name='ngo_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
