# Generated by Django 4.2.7 on 2026-02-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_funding_blockchain_tx_and_more'),
        ('api', '0008_distribution_face_scan_photo'),
    ]

    operations = [
    ]
