# Generated by Django 4.2.7 on 2026-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_beneficiary_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desired_donors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
