# Generated by Django 4.2.7 on 2026-03-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_desired_donors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Distribution', 'verbose_name_plural': 'Distributions'},
        ),
        migrations.AlterModelOptions(
            name='fieldofficerassignment',
            options={'verbose_name': 'Field Officer Assignment', 'verbose_name_plural': 'Field Officer Assignments'},
        ),
        migrations.AlterModelOptions(
            name='funding',
            options={'verbose_name': 'Funding', 'verbose_name_plural': 'Fundings'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='publicreport',
            options={'verbose_name': 'Public Report', 'verbose_name_plural': 'Public Reports'},
        ),
        migrations.AlterModelOptions(
            name='supplierassignment',
            options={'verbose_name': 'Supplier Assignment', 'verbose_name_plural': 'Supplier Assignments'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_FUNDING', 'Pending Funding'), ('FUNDED', 'Funded'), ('QUOTE_REQUESTED', 'Quote Requested'), ('QUOTES_RECEIVED', 'Quotes Received'), ('QUOTE_SELECTED', 'Quote Selected'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('FIELD_OFFICER_CONFIRMED', 'Field Officer Confirmed'), ('READY_FOR_DISTRIBUTION', 'Ready for Distribution'), ('IN_DISTRIBUTION', 'In Distribution'), ('COMPLETED', 'Completed')], default='PENDING_FUNDING', max_length=30),
        ),
        migrations.CreateModel(
            name='SupplyQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('proposed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_requirements', models.TextField(blank=True)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='api.project')),
            ],
            options={
                'verbose_name': 'Supply Quote Request',
                'verbose_name_plural': 'Supply Quote Requests',
                'db_table': 'supply_quote_requests',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_terms', models.TextField()),
                ('signature', models.CharField(max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='api.supplyquoterequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quotes', to='api.user')),
            ],
            options={
                'verbose_name': 'Supplier Quote',
                'verbose_name_plural': 'Supplier Quotes',
                'db_table': 'supplier_quotes',
            },
        ),
        migrations.CreateModel(
            name='QuoteSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_signature', models.CharField(max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_selections', to='api.user')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.supplyquoterequest')),
                ('selected_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.supplierquote')),
            ],
            options={
                'verbose_name': 'Quote Selection',
                'verbose_name_plural': 'Quote Selections',
                'db_table': 'quote_selections',
            },
        ),
    ]
