# Generated by Django 4.2.7 on 2026-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_beneficiary_options_alter_distribution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquoterequest',
            name='proposed_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
