# Generated by Django 4.2.7 on 2026-03-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20260303_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquoterequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SELECTED', 'Selected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
