# Generated by Django 4.2.7 on 2026-03-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_status_to_quote_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_signature', models.CharField(max_length=255)),
                ('delivery_notes', models.TextField(blank=True)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to='api.user')),
                ('quote_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmations', to='api.quoteselection')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmations', to='api.user')),
            ],
            options={
                'verbose_name': 'Supplier Delivery Confirmation',
                'verbose_name_plural': 'Supplier Delivery Confirmations',
                'db_table': 'supplier_delivery_confirmations',
            },
        ),
    ]
