# Generated by Django 4.2.7 on 2026-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_supplierdeliveryconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_FUNDING', 'Pending Funding'), ('FUNDED', 'Funded'), ('QUOTE_REQUESTED', 'Quote Requested'), ('QUOTES_RECEIVED', 'Quotes Received'), ('QUOTE_SELECTED', 'Quote Selected'), ('SUPPLIER_DELIVERED', 'Supplier Delivered'), ('FIELD_OFFICER_CONFIRMED', 'Field Officer Confirmed'), ('READY_FOR_DISTRIBUTION', 'Ready for Distribution'), ('IN_DISTRIBUTION', 'In Distribution'), ('COMPLETED', 'Completed')], default='PENDING_FUNDING', max_length=30),
        ),
    ]
