# Generated by Django 4.2.7 on 2026-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='ngo_confirmation_tx',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
