# Generated by Django 4.2.7 on 2026-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_funding_ngo_confirmation_tx'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='delivery_timeline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='quality_certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='supplier_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='technical_specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
