# Generated by Django 4.2.7 on 2026-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='document1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='document2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='document2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='document3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='document3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
