# Generated by Django 4.2.7 on 2026-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='face_descriptor',
            field=models.TextField(blank=True),
        ),
    ]
