# Generated by Django 4.2.7 on 2026-03-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_beneficiary_face_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiaries_csv',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiaries_csv_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
