# Generated by Django 4.2.7 on 2026-03-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_project_beneficiaries_csv_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name='supply_quote_requests' AND column_name='proposed_budget') THEN
                    -- Column exists, do nothing
                ELSE
                    ALTER TABLE supply_quote_requests ADD COLUMN proposed_budget DECIMAL(12,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE supply_quote_requests DROP COLUMN IF EXISTS proposed_budget;"
        ),
    ]
