# Generated by Django 4.2.7 on 2026-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20260308_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicreport',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
